apiVersion: apps/v1
kind: Deployment
metadata:
  name: ht-autenticador
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ht-autenticador
  template:
    metadata:
      labels:
        app: ht-autenticador
    spec:
      containers:
      - name: ht-autenticador
        image: brunobucci/ht-autenticador:latest  # Ajuste para sua imagem no Docker Hub
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "800m"
            memory: "512Mi"
        env:
        - name: SPRING_DATASOURCE_URL
          value: "mongodb://ht-mongo-usuario:27017/usuarios"
---
apiVersion: v1
kind: Service
metadata:
  name: ht-autenticador
spec:
  selector:
    app: ht-autenticador
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Porta fixa para acesso externo
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ht-autenticador-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ht-autenticador
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
