apiVersion: apps/v1
kind: Deployment
metadata:
  name: ht-video-extrator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ht-video-extrator
  template:
    metadata:
      labels:
        app: ht-video-extrator
    spec:
      containers:
      - name: ht-video-extrator
        image: brunobucci/ht-video-extrator:latest  # Ajuste para sua imagem no Docker Hub
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "800m"
            memory: "512Mi"
        env:
        - name: RABBITMQ_HOST
          value: "ht-fila"
---
apiVersion: v1
kind: Service
metadata:
  name: ht-video-extrator
spec:
  selector:
    app: ht-video-extrator
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082  # Porta fixa para acesso externo
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ht-video-extrator-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ht-video-extrator
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
